$('.owl-carousel').owlCarousel({
    autoplay:1000,
    loop:true,
    // margin:10,
    nav:false,
    dots:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        820:{
            items:2
        },
        1000:{
            items:3
        }
    }
})